name: MLOPS - Scoring Deployment

on:
  workflow_dispatch:
    inputs:
      client:
        required: true
        type: choice
        options:
          - all
          - cna
          - sedgwick
      image_tag:
        type: string
        required: true
      environment:
        required: true
        type: choice
        options:
          - all
          - development
          - staging
          - production
  workflow_call:
    inputs: 
      client:
        required: true
        type: string
      image_tag:
        required: true
        type: string                      
      environment:
        required: true
        type: string

env:
  DEPLOY_TARGET_CLIENT_TARGET_ENV: ${{ inputs.client != 'all' && inputs.environment != 'all' }} 
  DEPLOY_TARGET_CLIENT_ALL_ENV: ${{ inputs.client != 'all' && inputs.environment == 'all' }}
  DEPLOY_ALL_CLIENT_TARGET_ENV: ${{ inputs.client == 'all' && inputs.environment != 'all' }}
  DEPLOY_ALL_CLIENT_ALL_ENV: ${{ inputs.client == 'all' && inputs.environment == 'all' }}

jobs:
  mlops_deploy_target_client_all_env:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "what is this"
        echo "[ERROR] ${{ github.env.DEPLOY_TARGET_CLIENT_TARGET_ENV }}"
        echo "[ERROR] ${{ github.env.DEPLOY_TARGET_CLIENT_ALL_ENV }}"
        echo "[ERROR] ${{ github.env.DEPLOY_ALL_CLIENT_TARGET_ENV }}"
        echo "[ERROR] ${{ github.env.DEPLOY_ALL_CLIENT_ALL_ENV }}"

  # mlops_deploy_target_client_target_env:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.env.DEPLOY_TARGET_CLIENT_TARGET_ENV }}
  #   environment: ${{ inputs.environment }}
  #   steps:
  #     # TODO: enter validate prior deployment step
  #     - uses: EvolutionIQ/devops/.github/actions/dagster-deploy-code-location@main
  #       env:
  #         GIT_BOT_SSH_KEY: ${{ secrets.GIT_BOT_SSH_KEY }}
  #       with:
  #         location_name: ${{ inputs.client }}-ml-wc-scoring
  #         platform: GCP
  #         country_code: US
  #         environment: ${{ inputs.environment }}
  #         image_tag: ${{ inputs.image_tag }}                      

  # mlops_deploy_all_client_target_env:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.env.DEPLOY_ALL_CLIENT_TARGET_ENV }}
  #   environment: ${{ inputs.environment }}
  #   strategy:
  #     fail-fast: true
  #     max-parallel: 1
  #     matrix:
  #       client:
  #         - cna
  #         - sedgwick      
  #   steps:
  #     # TODO: enter validate prior deployment step
  #     - uses: EvolutionIQ/devops/.github/actions/dagster-deploy-code-location@main
  #       env:
  #         GIT_BOT_SSH_KEY: ${{ secrets.GIT_BOT_SSH_KEY }}
  #       with:
  #         location_name: ${{ matrix.client }}-ml-wc-scoring
  #         platform: GCP
  #         country_code: US
  #         environment: ${{ inputs.environment }}
  #         image_tag: ${{ inputs.image_tag }}  

  # mlops_deploy_all_development:
  #   runs-on: ubuntu-latest     
  #   if: ${{ github.env.DEPLOY_ALL_CLIENT_ALL_ENV }}
  #   environment: development
  #   strategy:
  #     fail-fast: true
  #     max-parallel: 1
  #     matrix:
  #       client:
  #         - cna
  #         - sedgwick
  #   steps:
  #     - uses: EvolutionIQ/devops/.github/actions/dagster-deploy-code-location@main
  #       env:
  #         GIT_BOT_SSH_KEY: ${{ secrets.GIT_BOT_SSH_KEY }}
  #       with:
  #         location_name: ${{ matrix.client }}-ml-wc-scoring
  #         platform: GCP
  #         country_code: US
  #         environment: development
  #         image_tag: ${{ inputs.image_tag }}    

  # mlops_deploy_all_staging:
  #   runs-on: ubuntu-latest     
  #   needs: 
  #     - mlops_deploy_all_development
  #   environment: staging
  #   strategy:
  #     fail-fast: true
  #     max-parallel: 1
  #     matrix:
  #       client:
  #         - cna
  #         - sedgwick
  #   steps:
  #     - run: echo "hello"
